apps/base/urls.py
from django.urls import path
from apps.base.views import index

app_name = "base"
urlpatterns = [
    path('', index, name='home'),
]

apps/core/urls.py
from django.urls import path
from apps.core.views import show_list, show_detail, show_discover, show_vote

app_name = "core"
urlpatterns = [
    path('top-100/', show_list, name='top-100'),
    path('details/<int:pk>', show_detail, name='show-detail'),
    path('discover/', show_discover, name='show-discover'),
    path('vote/<int:pk>', show_vote, name='show-vote'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.base import urls as base_urls
from apps.core import urls as core_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(base_urls)),
    path('', include(core_urls)),
]

apps/base/models.py
# Create your models here.

apps/core/models.py
from django.db import models


class Show(models.Model):
    show_id = models.IntegerField()
    name = models.CharField(max_length=255)
    description = models.TextField()
    poster = models.CharField(max_length=255)
    popularity = models.CharField(max_length=255)
    votes = models.IntegerField()
    release_year = models.DateField()

    def __str__(self):
        return self.name


class ShowDetail(models.Model):
    show_id = models.IntegerField()
    name = models.CharField(max_length=255)
    description = models.TextField()
    poster = models.CharField(max_length=255)
    popularity = models.CharField(max_length=255)
    release_year = models.DateField()
    release_date_first_epi = models.DateField()
    total_epi = models.IntegerField()
    gender = models.TextField()
    # gender = models.ManyToManyField('Gender')

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(max_length=255)


class Reviews(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    rating = models.IntegerField()
    avatar_path = models.CharField(max_length=255)

apps/core/forms.py
from django import forms


class VoteForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255)
    rating = forms.IntegerField(min_value=0, max_value=10)

apps/base/views.py
from django.shortcuts import render


def index(request):
    return render(request, template_name="base/home.html")

apps/core/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.core.forms import VoteForm
from apps.core.services.show_detail import get_show_detail, get_show_reviews
from apps.core.services.show_list import get_show_list
from apps.core.services.show_vote import set_show_vote


def show_list(request):
    data = get_show_list()
    paginator = Paginator(data, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, template_name="core/show_list.html", context=context)


def show_detail(request, pk):

    context = {'item': get_show_detail(pk),
               'reviews': get_show_reviews(pk)}
    return render(request, template_name="core/show_detail.html", context=context)


def show_vote(request, pk):
    form = VoteForm(request.POST)

    if form.is_valid():
        set_show_vote(obj_id=pk,
                      username=form.cleaned_data["username"],
                      password=form.cleaned_data["password"],
                      rating=form.cleaned_data["rating"])
        messages.success(request, 'Your review has been successfully sent!')
        return redirect(reverse('core:top-100'))

    messages.error(request, 'Failed. Please check your inputs again!')
    return redirect(reverse('core:show-detail', args=[pk]))


def show_discover(request, show_name=None, release_year=None, popularity=None):

    return render(request, template_name="core/show_discover.html")

apps/base/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="author" content="Rodrigo Delfino de Carvalho">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="job application test">
    <link rel="shortcut icon" href="https://cdn.b2blue.com/p/static/img/sistema/favicon.ico" />
    <title>{% block title %} {% endblock %}</title>


<!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- Fontawesome -->
<script src="https://kit.fontawesome.com/7929258011.js" crossorigin="anonymous"></script>


<body class="bg-light">

{% include 'base/navbar.html' %}

<main role="main">
{% block content %}
{% endblock %}
</main>

{% include 'base/footer.html' %}

{% block script %}
{% endblock %}

</body>
</html>

apps/base/templates/base/footer.html
{% load static %}
<footer class="footer mt-5 py-3 bg-dark">
  <div class="container">
    <a href="https://github.com/rodrigoddc/" class="link-secondary"><span class="text-muted">by Rodrigo Delfino de Carvalho</span></a>
  </div>
</footer>

apps/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} B2blue - TMDB API integration{% endblock %}



{% block content %}

<header>
    <section class="px-4 py-5 my-5 text-center min-vh-100">
<!--        <img class="d-block mx-auto mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">-->
        <h1 class="display-5 fw-bold">The Movie Database API integration</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead my-4">A B2blue test application.</p>
            <p class="lead mb-4">Develop by Rodrigo Delfino de Carvalho, this app will integrate you with TMDB, providing many functionalits in a single click.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="{% url 'core:top-100'%}" class="btn btn-outline-secondary btn-lg px-4">Check top 100 popular TV shows</a>
            </div>
            <p class="lead my-4">*Explore the series detail, and you'll be able to rating on it from there!</p>
        </div>
    </section>
</header>


{% endblock %}

apps/base/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
    <div class="container-fluid">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar01" aria-controls="navbar01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse justify-content-md-center collapse" id="navbar01" style="">
        <ul class="navbar-nav pt-4 pb-2">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'base:home' %}"><span class="h5 fw-bolder text-info">B2blue</span></a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown08" data-bs-toggle="dropdown" aria-expanded="false">Options</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown08">
              <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
              <li><a class="dropdown-item" href="{% url 'base:home' %}">Home</a></li>
              <li><a class="dropdown-item" href="{% url 'core:top-100' %}">Top 100 tv series</a></li>
              <li><a class="dropdown-item" href="{% url 'core:show-discover' %}">Discover - <i>under construction</i></a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

apps/core/templates/core/show_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} B2blue {% endblock %}



{% block content %}

<header>

    <section class="container px-4 pb-5 my-5 text-center">
        {% if messages %}
        {% for message in messages %}
            <div class="alert text-center {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
        {% endif %}

        <h1 class="fw-bold pb-3">This show in detail!</h1>
        <div class="row">
            <div class="col-md-5 h-100">
                <img src="{{ item.poster }}" class="img-fluid" alt="...">
            </div>
            <div class="col-md-7">
                <div class="col-12">
                    <div class="card border-secondary mb-3 h-100">
                        <div class="card-header"><h5 class="card-title">{{ item.name }}</h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ item.description }}</p>
                            <p class="card-text">Popularity: {{ item.popularity }}</p>
                            <p class="card-text">Year: {{ item.release_year }}</p>
                            <p class="card-text">First episode release: {{ item.release_date_first_epi }}</p>
                            <p class="card-text">Total episodes: {{ item.total_epi }}</p>
                            <p class="card-text">Geners: {{ item.gender }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 ">
                    <div class="card border-secondary mb-3">
                        <div class="card-body text-secondary">
                            <h5 class="card-title">Add your review!</h5>
                            <form method="POST" action="{% url 'core:show-vote' item.show_id %}" class="row g-3 " >
                                {% csrf_token %}
                                <div class="col-6">
                                    <label for="username" class="form-label">Username</label>
                                    <input name="username" type="text" class="form-control" id="username" placeholder="my_username">
                                </div>
                                <div class="col-6">
                                    <label for="password" class="form-label">Password</label>
                                    <input name="password" type="password" class="form-control" id="password" placeholder="******">
                                </div>
                                <div class="col-md-12">
                                    <div class="row row-cols-lg-auto g-3 align-items-center">
                                        <div class="col-2">
                                            <label for="rating" class="col-form-label">Rating</label>
                                        </div>
                                        <div class="col-10">
                                            <input name="rating" type="text" pattern="[0-9]{,10}" class="form-control" id="rating" placeholder="Ex: 5.0">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-outline-success btn-lg px-4"><i class="fas fa-vote-yea"></i>Vote!</button>
                                </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            {% for item in reviews %}
            <div class="col-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="{{ item.avatar_path }}" role="img">
                <h2>{{ item.name }}</h2>
                <p class="card-text">{{ item.description }}</p>
                <p class="card-text">{{ item.rating }}</p>
            </div>
            {% endfor %}
        </div>

    </section>
</header>


{% endblock %}

apps/core/templates/core/show_discover.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} B2blue - TMDB API integration{% endblock %}



{% block content %}

<header>
    <section class="px-4 pb-5 my-5 text-center min-vh-100">
        <div class="alert alert-warning" role="alert">
            This page is under construction
        </div>

        <h1 class="display-5 fw-bold">Find the what you are looking for!</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead my-4">Here you can filter then by name, release year and/or popularity order</p>
            <form action="{% url 'core:show-discover' %}" method="GET">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <label for="show-name" class="form-label">Program name</label>
                        <input id="show-name" name="show_name" type="text" class="form-control" placeholder="Ex: Matrix" aria-label="program name" aria-describedby="button-addon1">
                    </div>
                    <div class="col-md-4">
                        <label for="release-year" class="form-label">Release year</label>
                        <input id="release-year" name="release_year" type="text" pattern="[0-9]+{4}" class="form-control" placeholder="Ex: 2021" aria-label="popularity" aria-describedby="button-addon1">
                    </div>
                    <div class="col-md-4">
                        <label for="popularity" class="form-label">Popularity value</label>
                        <input id="popularity" name="popularity" type="text" pattern="[0-9].{,10}+" class="form-control" placeholder="Ex: 100" aria-label="popularity" aria-describedby="button-addon1">
                    </div>
                </div>
                <div class="row my-5">
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                        <button type="button" class="btn btn-outline-secondary btn-lg px-4"><i class="fas fa-search"></i> Search</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-6 mx-auto">
            {% if context %}
            <p>{{ context }}</p>
            {% endif %}
        </div>


    </section>
</header>


{% endblock %}

apps/core/templates/core/show_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} B2blue {% endblock %}



{% block content %}

<header>
    <section class="container px-4 py-5 my-3 text-center">
        <h1 class="fw-bold">Top 100 popular TV series!</h1>

        <nav class="mt-5" aria-label="pagination">
            <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                {% endif %}

                {% for pg in page_obj.paginator.page_range %}
                {% if pg == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>

        <div class="row row-cols-1 row-cols-md-5 g-4">
            {% for item in page_obj %}
            <div class="col">
                <div class="card h-100">
                    <img src="{{ item.poster }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text text-truncate">{{ item.description }}</p>
                        <p class="card-text">Popularity: <span class="fw-bold">{{ item.popularity }}</span></p>
                        <p class="card-text">Votes: <span class="fw-bold">{{ item.votes }}</span></p>
                        <span class="card-text">Year: <span class="fw-bold">{{ item.release_year }}</span></span>
                    </div>
                    <div class="card-footer bg-dark">
                        <a href="{% url 'core:show-detail' item.show_id %}" class="nav-link text-light"><i class="fas fa-info-circle"></i> Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <nav class="mt-5" aria-label="pagination">
            <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                {% endif %}

                {% for pg in page_obj.paginator.page_range %}
                {% if pg == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </section>
</header>


{% endblock %}

apps/core/templates/core/show_vote.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} B2blue - TMDB API integration{% endblock %}



{% block content %}

<header>
    <section class="px-4 py-5 my-5 text-center min-vh-100">
<!--        <img class="d-block mx-auto mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">-->
        <h1 class="display-5 fw-bold">The Movie Database API integration</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead my-4">A B2blue test application.</p>
            <p class="lead mb-4">Develop by Rodrigo Delfino de Carvalho, this app will integrate you with TMDB, providing many functionalits in a single click.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="{% url 'core:top-100'%}" class="btn btn-outline-secondary btn-lg px-4">Check top 100 popular TV shows</a>
            </div>
        </div>
    </section>
</header>


{% endblock %}